# Generated by Django 4.1.4 on 2024-03-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('place', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('exp', models.CharField(default='', max_length=100)),
                ('specialization', models.CharField(default='', max_length=100)),
                ('start_time', models.CharField(default='', max_length=100)),
                ('end_time', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('place', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
