# Generated by Django 4.1.4 on 2024-03-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
