# Generated by Django 4.1.4 on 2024-03-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0002_tbl_doctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
