# Generated by Django 4.1.4 on 2024-03-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0003_alter_tbl_doctor_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_DoctorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_register')),
            ],
        ),
    ]
