# Generated by Django 4.1.4 on 2024-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0004_tbl_doctorbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='appointment_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
