# Generated by Django 4.1.4 on 2024-03-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0005_alter_tbl_doctorbooking_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_register',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='tbl_register',
            name='gender',
        ),
    ]
