# Generated by Django 4.1.4 on 2024-03-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0006_remove_tbl_register_dob_remove_tbl_register_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_doctor',
            name='gender',
        ),
    ]
