# Generated by Django 4.1.4 on 2024-03-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0007_remove_tbl_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='end_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='start_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
