# Generated by Django 4.1.4 on 2024-03-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0008_alter_tbl_doctor_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
