# Generated by Django 4.1.4 on 2024-03-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0009_alter_tbl_doctor_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_doctor_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_doctor')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_register')),
            ],
        ),
    ]
