# Generated by Django 4.1.4 on 2024-03-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0010_tbl_doctor_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_doctorbooking',
            old_name='appointment_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='tbl_doctorbooking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='tbl_doctorbooking',
            name='patient',
        ),
        migrations.AddField(
            model_name='tbl_doctorbooking',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_doctorbooking',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_doctorbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_register'),
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_doctor'),
        ),
        migrations.DeleteModel(
            name='tbl_doctor_booking',
        ),
    ]
