# Generated by Django 4.1.4 on 2024-04-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0011_rename_appointment_time_tbl_doctorbooking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-01 00:20:46', max_length=100),
        ),
    ]
