# Generated by Django 4.1.4 on 2024-04-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0013_alter_tbl_doctorbooking_created_at_tbl_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-02 09:11:31', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-02 09:11:31', max_length=100),
        ),
    ]
