# Generated by Django 4.1.4 on 2024-04-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0014_tbl_usernote_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctor',
            name='end_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctor',
            name='start_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-02 09:18:43', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-02 09:18:43', max_length=100),
        ),
    ]
