# Generated by Django 4.1.4 on 2024-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0015_alter_tbl_doctor_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctor',
            name='utype',
            field=models.CharField(default='doctor', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_register',
            name='utype',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-02 09:24:53', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-02 09:24:53', max_length=100),
        ),
    ]
