# Generated by Django 4.1.4 on 2024-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0017_tbl_doctorbooking_note_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_doctorbooking',
            name='note_status',
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-09 07:11:04', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-09 07:11:04', max_length=100),
        ),
    ]
