# Generated by Django 4.1.4 on 2024-04-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0018_remove_tbl_doctorbooking_note_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_usernote',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_doctorbooking'),
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-09 07:19:12', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-09 07:19:12', max_length=100),
        ),
    ]
