# Generated by Django 4.1.4 on 2024-04-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0019_tbl_usernote_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_doctorbooking',
            name='note_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-09 10:36:17', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-09 10:36:17', max_length=100),
        ),
    ]
