# Generated by Django 4.1.4 on 2024-04-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0020_tbl_doctorbooking_note_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-09 10:40:02', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-09 10:40:02', max_length=100),
        ),
    ]
