# Generated by Django 4.1.4 on 2024-04-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0022_alter_tbl_doctorbooking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-16 06:24:45', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-16 06:24:45', max_length=100),
        ),
        migrations.CreateModel(
            name='tbl_userrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(default='')),
                ('rating', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_register')),
            ],
        ),
    ]
