# Generated by Django 5.0.3 on 2024-04-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0024_alter_tbl_doctorbooking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-30 05:28:52', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-30 05:28:52', max_length=100),
        ),
        migrations.CreateModel(
            name='tbl_emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(default='', max_length=100)),
                ('emotionfile', models.ImageField(default='null.jpeg', upload_to='emotion')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emotionapp.tbl_register')),
            ],
        ),
    ]
