# Generated by Django 5.0.3 on 2024-04-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0025_alter_tbl_doctorbooking_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_emotiondetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(default='', max_length=100)),
                ('emotionfile', models.ImageField(default='null.jpeg', upload_to='emotion')),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-04-30 05:33:58', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-04-30 05:33:58', max_length=100),
        ),
    ]
