# Generated by Django 5.0.4 on 2024-05-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionapp', '0027_alter_tbl_doctorbooking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_doctorbooking',
            name='created_at',
            field=models.CharField(default='2024-05-07 07:48:46', max_length=100),
        ),
        migrations.AlterField(
            model_name='tbl_usernote',
            name='created_at',
            field=models.CharField(default='2024-05-07 07:48:46', max_length=100),
        ),
    ]
